/**
 * Green Room — shared type definitions.
 *
 * Green Room is the live-classroom feature (scheduling, joining, and running a
 * real-time video meeting). It is deliberately self-contained under
 * `lib/greenroom/` so it can evolve without touching exams, proctoring, or
 * classrooms.
 */
import { FirestoreDate } from "@/lib/types";

/**
 * A participant's authority inside one meeting.
 *
 * This is NOT the app-level role (`student`/`teacher`/`admin`). A teacher who
 * joins someone else's Green Room is a plain `participant` there; the meeting
 * role is assigned by the server at join time and stored on the participant
 * document, where a client cannot write it.
 */
export type MeetingRole = "host" | "cohost" | "participant";

/**
 * Where a participant is in the join lifecycle.
 *
 * `waiting` exists only when the meeting has its waiting room enabled — the
 * server parks the participant there and a host must `admit` them before any
 * media is exchanged.
 */
export type ParticipantState =
  | "waiting"
  | "admitted"
  | "joined"
  | "left"
  | "removed"
  | "rejected";

export type MeetingStatus = "scheduled" | "live" | "ended" | "cancelled";

/** Host-controlled meeting policy. Enforced server-side, not by hiding buttons. */
export interface MeetingSettings {
  /** Park joiners in a waiting room until a host admits them. */
  waitingRoom: boolean;
  /** Allow participants to enter before the host has started the meeting. */
  joinBeforeHost: boolean;
  /** May non-host participants share their screen? */
  allowParticipantScreenShare: boolean;
  /** May participants send chat messages? */
  allowChat: boolean;
  /** May participants send reactions / raise a hand? */
  allowReactions: boolean;
  /**
   * May participants unmute themselves? When false a host must explicitly
   * request unmute — the standard "muted on entry, lecture mode" setup.
   */
  allowParticipantUnmute: boolean;
  /**
   * Room-wide audio-only mode. Suppresses video publication for everyone,
   * which is the main lever for getting more people into a mesh meeting
   * (see `MAX_MESH_PARTICIPANTS` in ./constants).
   */
  audioOnly: boolean;
  /** No new participants may join, regardless of passcode. */
  locked: boolean;
}

export interface Meeting {
  id: string;
  title: string;
  description?: string;

  /** Human-facing meeting id, formatted `123-456-789`. Unique. */
  meetingCode: string;

  /** Owning teacher — always the initial host. */
  teacherId: string;
  teacherName: string;

  /** Optional course association, used for student eligibility. */
  courseId?: string;
  courseName?: string;
  /** Optional classroom association — members of it are eligible to join. */
  classroomId?: string;

  status: MeetingStatus;
  settings: MeetingSettings;

  /** Scheduled start. For an instant meeting this is the creation time. */
  scheduledStart: FirestoreDate;
  durationMinutes: number;

  /** Set when the host actually starts / ends the meeting. */
  startedAt?: FirestoreDate;
  endedAt?: FirestoreDate;

  /** Denormalized live counter, maintained server-side. */
  activeParticipantCount?: number;

  createdAt: FirestoreDate;
  updatedAt: FirestoreDate;
}

/**
 * One person's presence in one meeting.
 *
 * Document id is deterministic: `${meetingId}_${userId}`. That makes rejoining
 * idempotent and lets rules check "is this my own participant doc" without a
 * read.
 */
export interface MeetingParticipant {
  id: string;
  meetingId: string;
  userId: string;
  name: string;
  email?: string;
  /** App-level role, denormalized for display (badges, sorting). */
  appRole: "student" | "teacher" | "admin";

  /** Server-assigned. Never writable by a client. */
  role: MeetingRole;
  /** Server-assigned. Never writable by a client. */
  state: ParticipantState;

  // --- self-reported media state (client may write these on its own doc) ---
  micOn: boolean;
  camOn: boolean;
  handRaised: boolean;
  screenSharing: boolean;
  /** Heartbeat, used to detect participants who vanished without leaving. */
  lastSeenAt?: FirestoreDate;

  // --- attendance (server-written) ---
  firstJoinedAt?: FirestoreDate;
  joinedAt?: FirestoreDate;
  leftAt?: FirestoreDate;
  /** Accumulated across reconnects. */
  totalDurationMs?: number;
  reconnects?: number;

  createdAt: FirestoreDate;
  updatedAt: FirestoreDate;
}

export interface MeetingMessage {
  id: string;
  meetingId: string;
  senderId: string;
  senderName: string;
  text: string;
  /** `system` messages are generated by moderation actions, not typed. */
  type: "chat" | "system";
  createdAt: FirestoreDate;
}

export type ReactionKind =
  | "thumbsUp"
  | "heart"
  | "laugh"
  | "clap"
  | "celebrate"
  | "surprised";

export interface MeetingReaction {
  id: string;
  meetingId: string;
  senderId: string;
  senderName: string;
  kind: ReactionKind;
  createdAt: FirestoreDate;
}

/** Moderation verbs accepted by `/api/greenroom/moderate`. */
export type ModerationAction =
  | "admit"
  | "reject"
  | "mute"
  | "requestUnmute"
  | "remove"
  | "promote"
  | "demote"
  | "lowerHand"
  | "updateSettings"
  | "start"
  | "end";

/** Attendance summary shown to a teacher after the meeting. */
export interface AttendanceRow {
  userId: string;
  name: string;
  email?: string;
  firstJoinedAt?: FirestoreDate;
  leftAt?: FirestoreDate;
  totalDurationMs: number;
  reconnects: number;
  /** Derived from `totalDurationMs` against the meeting's actual length. */
  status: "present" | "partial" | "absent";
}
